"""Public contract for evidence-backed firmware communication mapping."""

from .domain import (
    AnalyzerIdentity,
    ClaimStatus,
    CoverageEntry,
    CoverageStatus,
    DiagnosticSeverity,
    EvidenceAtom,
    EvidenceSpan,
    FirmwareMappingSnapshot,
    MappingBudget,
    MappingDiagnostic,
    MappingEntity,
    MappingMode,
    MappingPolicy,
    ObservationKind,
    ObligationStatus,
    SemanticRelation,
    SNAPSHOT_SCHEMA_VERSION,
    SnapshotStatus,
    UnresolvedObligation,
)

__all__ = (
    "AnalyzerIdentity",
    "ClaimStatus",
    "CoverageEntry",
    "CoverageStatus",
    "DiagnosticSeverity",
    "EvidenceAtom",
    "EvidenceSpan",
    "FirmwareMappingSnapshot",
    "MappingBudget",
    "MappingDiagnostic",
    "MappingEntity",
    "MappingMode",
    "MappingPolicy",
    "ObservationKind",
    "ObligationStatus",
    "SemanticRelation",
    "SNAPSHOT_SCHEMA_VERSION",
    "SnapshotStatus",
    "UnresolvedObligation",
)
